### ISSUE TITLE
Moon64 Controller compatibility problems

### ISSUE THREAD

**Issue by eros71-dev** [KiritoDv/Moon64#1]
**Describe the bug**
The controls are all mixed up when using a DualShock 4 (PS4 Controller) when using a cable.
Mario is always crouching, the and Mario's head in the title tilts up.

Also, I've used the moon64_60fps patch.

The render96 repo and sm64ex don't have any problems with it and work as expected.

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - (Maybe the repo is not compatible with windows 10 fully yet, sorry if that's the case)

[EDIT: Using a tool like DS4Windows seems to be a workaround, but it still weird that it happens]

**Comment by KiritoDv** [comment]
Can you try again on master without ds4? Its weird because im using the same controller db we use on r96

**Comment by eros71-dev** [comment]
Nope, it still doesn't work (only using the controller with a cable, without ds4windows or anything else) , I tried the lastest render96 repo version and it does work there. Weird.
